default: &default
  adapter: postgresql

development:
  <<: *default
  database: scaleapp_development

test:
  <<: *default
  database: scaleapp_test

production:
  <<: *default
  database: scaleapp_production
